"""empty message

Revision ID: 0c1e0c3ad00d
Revises: 408176b91ad3
Create Date: 2024-07-12 03:10:31.811623

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c1e0c3ad00d'
down_revision = '408176b91ad3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dataset_permissions',
    sa.Column('id', models.StringUUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('dataset_id', models.StringUUID(), nullable=False),
    sa.Column('account_id', models.StringUUID(), nullable=False),
    sa.Column('tenant_id', models.StringUUID(), nullable=False),
    sa.Column('has_permission', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name='dataset_permission_pkey')
    )
    with op.batch_alter_table('dataset_permissions', schema=None) as batch_op:
        batch_op.create_index('idx_dataset_permissions_account_id', ['account_id'], unique=False)
        batch_op.create_index('idx_dataset_permissions_dataset_id', ['dataset_id'], unique=False)
        batch_op.create_index('idx_dataset_permissions_tenant_id', ['tenant_id'], unique=False)

    with op.batch_alter_table('apps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_active_requests', sa.Integer(), nullable=True))

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index('message_workflow_run_id_idx', ['conversation_id', 'workflow_run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index('message_workflow_run_id_idx')

    with op.batch_alter_table('apps', schema=None) as batch_op:
        batch_op.drop_column('max_active_requests')

    with op.batch_alter_table('dataset_permissions', schema=None) as batch_op:
        batch_op.drop_index('idx_dataset_permissions_tenant_id')
        batch_op.drop_index('idx_dataset_permissions_dataset_id')
        batch_op.drop_index('idx_dataset_permissions_account_id')

    op.drop_table('dataset_permissions')
    # ### end Alembic commands ###
