"""empty message

Revision ID: 35400bd925c6
Revises: eeb2e349e6ac
Create Date: 2024-08-07 13:36:00.493115

"""
import sqlalchemy as sa
from alembic import op

import models as models

# revision identifiers, used by Alembic.
revision = '35400bd925c6'
down_revision = 'eeb2e349e6ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dataset_collection_bindings', schema=None) as batch_op:
        batch_op.alter_column('model_name',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=255),
               existing_nullable=False)

    with op.batch_alter_table('embeddings', schema=None) as batch_op:
        batch_op.alter_column('model_name',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=255),
               existing_nullable=False,
               existing_server_default=sa.text("'text-embedding-ada-002'::character varying"))
        batch_op.alter_column('provider_name',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=255),
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
        batch_op.create_index('created_at_idx', ['created_at'], unique=False)

    with op.batch_alter_table('trace_app_config', schema=None) as batch_op:
        batch_op.drop_index('tracing_app_config_app_id_idx')
        batch_op.create_index('trace_app_config_app_id_idx', ['app_id'], unique=False)

    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('environment_variables', sa.Text(), server_default='{}', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.drop_column('environment_variables')

    with op.batch_alter_table('trace_app_config', schema=None) as batch_op:
        batch_op.drop_index('trace_app_config_app_id_idx')
        batch_op.create_index('tracing_app_config_app_id_idx', ['app_id'], unique=False)

    with op.batch_alter_table('embeddings', schema=None) as batch_op:
        batch_op.drop_index('created_at_idx')
        batch_op.alter_column('provider_name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=40),
               existing_nullable=False,
               existing_server_default=sa.text("''::character varying"))
        batch_op.alter_column('model_name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=40),
               existing_nullable=False,
               existing_server_default=sa.text("'text-embedding-ada-002'::character varying"))

    with op.batch_alter_table('dataset_collection_bindings', schema=None) as batch_op:
        batch_op.alter_column('model_name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=40),
               existing_nullable=False)

    # ### end Alembic commands ###
