name: Build Push API TO TEST

on:
  push:
    branches:
      - dev
  workflow_dispatch:

env:
  hub: ccr.ccs.tencentyun.com
  namespace: invest_x
  context: ./api
  image_name: dify-api
  image_tag: 1.0
  image_url: ${{env.hub}}/${{env.namespace}}/${{env.image_name}}:${{env.image_tag}}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v1

      - name: Build Image
        run: docker build -t ${{env.image_url}} ./${{env.context}}/.

      - name: Login Registry
        run: docker login --username=${{secrets.TENCENT_DOCKER_USERNAME}} --password ${{ secrets.TENCENT_DOCKER_PASSWORD }} ${{hub}}

      - name: Push Image
        run: docker push ${{env.image_url}}

      - name: Get pre step result output image_pull_url
        run: echo "The time was ${{ steps.buildAndPushImage.outputs.image_pull_url }}"

      - name: Send Webhook
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=3654485c-fef1-4557-b124-8007ef1e15a5'
          method: 'POST'
          customHeaders: '{"Content-Type": "application/json"}'
          data: '{ "msgtype": "text", "text": { "content": "${{image_name}}:${{image_tag}}构建成功，可后续操作"} }'