name: Build Push Test

on:
  push:
    branches:
      - dev
  workflow_dispatch:

env:
  dockerhub_domain: "ccr.ccs.tencentyun.com"
  namespace: kennethcse
  context: ./api
  image_name: dify-api
  image_tag: 1.0
  image_url: kennethcse/dify-api:1.0
  dockerhub_user: ${{ secrets.TENCENT_DOCKER_USERNAME }}
  dockerhub_token: ${{ secrets.TENCENT_DOCKER_PASSWORD }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.dockerhub_domain }}
          username: ${{ env.dockerhub_user }}
          password: ${{ env.dockerhub_token }}

      - name: Pull Image
        run: docker pull kennethcse/dify-api:1.0

      - name: Docker Tag
        run: docker tag kennethcse/dify-api:1.0 ${{ env.image_url }}

      - name: Docker push
        run: docker push ${{ env.image_url }}

      - name: Get pre step result output image_pull_url
        run: echo "The time was ${{ steps.buildAndPushImage.outputs.image_pull_url }}"

      - name: Send Webhook
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=3654485c-fef1-4557-b124-8007ef1e15a5'
          method: 'POST'
          customHeaders: '{"Content-Type": "application/json"}'
          data: '{ "msgtype": "text", "text": { "content": "${{env.image_name}}:${{env.image_tag}}构建成功，可后续操作"} }'