name: Build Push API TO TEST

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v1

		  - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
					registry: ccr.ccs.tencentyun.com
          username: ${{ secrets.TENCENT_DOCKER_USERNAME }}
          password: ${{ secrets.TENCENT_DOCKER_PASSWORD }}
					
			- name: Extract Docker metadata
	      id: meta
	      uses: docker/metadata-action@v4
	      with:
	          images: "invest_x/dify-api"
	          tags: |
	            # set latest tag for default branch
	            type=raw,value=latest,enable={{is_default_branch}}
	            # tag event
	            type=ref,enable=true,priority=600,prefix=,suffix=,event=tag

	    - name: Build and push Docker images
		 		id: push
			  uses: docker/build-push-action@v6.5.0
			  with:
			    context: ./api
			    file: ./Dockerfile
			    push: true
			    tags: 1.0
          

      - name: Get pre step result output image_pull_url
        run: echo "The time was ${{ steps.buildAndPushImage.outputs.image_pull_url }}"

      - name: Send Webhook
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=3654485c-fef1-4557-b124-8007ef1e15a5'
          method: 'POST'
          customHeaders: '{"Content-Type": "application/json"}'
          data: '{ "msgtype": "text", "text": { "content": "dify-api构建成功，可后续操作"} }'
