name: PushCodeToGitlab
on:
  push:
    branches:
      - dev
      - main

jobs:
  sync-repo:
    runs-on: ubuntu-latest
    steps:
      - name: CheckOut
        uses: actions/checkout@v3

      - name: Install Git
        run: sudo apt-get install git

      - name: Push to GitLab
        env:
          GITLAB_URL: ${{ secrets.GITLAB_URL }}
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          BRANCH_NAME=${GITHUB_REF##*/}
          git remote add gitlab ${GITLAB_URL}/<your_gitlab_username>/<your_gitlab_repo>.git
          git push -u gitlab $BRANCH_NAME
